/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_du_cabinet_medical;

import java.awt.Color;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;

/**
 *
 * @author pc
 */
public class afficher_rdv extends javax.swing.JDialog {

    /**
     * Creates new form afficher_rdv
     */
    public afficher_rdv(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
            this.getContentPane().setBackground(Color.decode("#000"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        box1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        box2 = new javax.swing.JLabel();
        bodddx3 = new javax.swing.JPanel();
        box3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bdddox4 = new javax.swing.JPanel();
        box4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        box5 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        box6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cab5 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton3.setBackground(new java.awt.Color(102, 153, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("8 ==> 9");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 153, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("9 ==> 10");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 153, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setText("11 ==> 12");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 153, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setText("10 ==> 11");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(102, 153, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton7.setText("17 ==> 18");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 153, 255));
        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton8.setText("16 ==> 17");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 153, 255));
        jButton9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton9.setText("15 ==> 16");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(102, 153, 255));
        jButton10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton10.setText("14 ==> 15");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 110, 176, 583);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultation de Rendez Vous");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(304, 11, 601, 56);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        box1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/box1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        box2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/box2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        box3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/box3.jpg"))); // NOI18N

        javax.swing.GroupLayout bodddx3Layout = new javax.swing.GroupLayout(bodddx3);
        bodddx3.setLayout(bodddx3Layout);
        bodddx3Layout.setHorizontalGroup(
            bodddx3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodddx3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodddx3Layout.setVerticalGroup(
            bodddx3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodddx3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Box 2");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Reeducation 2");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Box 1");

        box4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/box4.jpg"))); // NOI18N

        javax.swing.GroupLayout bdddox4Layout = new javax.swing.GroupLayout(bdddox4);
        bdddox4.setLayout(bdddox4Layout);
        bdddox4Layout.setHorizontalGroup(
            bdddox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bdddox4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bdddox4Layout.setVerticalGroup(
            bdddox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bdddox4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Table Bobath");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bodddx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bdddox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel10)
                .addGap(155, 155, 155)
                .addComponent(jLabel8)
                .addGap(156, 156, 156)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(77, 77, 77))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bodddx3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdddox4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));

        box5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/box5.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        box6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/box6.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Table 4 plan");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Table bebe");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(109, 109, 109))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(194, 110, 946, 572);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date  :");

        cab5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cab5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cab5FocusLost(evt);
            }
        });
        cab5.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cab5VetoableChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(cab5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cab5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(194, 73, 891, 31);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1140, 670);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 10, 1160, 690);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1160, 700);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/arriereplan.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 1160, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
        try {
DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
 String date= df.format(cab5.getDate()); 
cabinetmedical cabinet=new cabinetmedical();
String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton3.getText()+"' and date_rdv='"+date+"'";
System.out.println(req_sql);
ResultSet rs_medical = cabinet.statement.executeQuery(req_sql); 

  while (rs_medical.next()) { 
 if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
 if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
 if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
 if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
 if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
  if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
}
 } catch (SQLException ex) {
ex.printStackTrace();
}
 afficher(box1,box2,box3,box4,box5,box6);


// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
        try {
DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
 String date= df.format(cab5.getDate()); 
cabinetmedical cabinet=new cabinetmedical();
String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton4.getText()+"' and date_rdv='"+date+"'";
System.out.println(req_sql);
ResultSet rs_medical = cabinet.statement.executeQuery(req_sql); 

  while (rs_medical.next()) { 
 if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
 if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
 if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
 if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
 if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
  if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
}
 } catch (SQLException ex) {
ex.printStackTrace();
}
 afficher(box1,box2,box3,box4,box5,box6);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
        try {
DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
 String date= df.format(cab5.getDate()); 
cabinetmedical cabinet=new cabinetmedical();
String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton5.getText()+"' and date_rdv='"+date+"'";
System.out.println(req_sql);
ResultSet rs_medical = cabinet.statement.executeQuery(req_sql); 

  while (rs_medical.next()) { 
 if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
 if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
 if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
 if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
 if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
  if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
}
 } catch (SQLException ex) {
ex.printStackTrace();
}
 afficher(box1,box2,box3,box4,box5,box6);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
        try {
DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
 String date= df.format(cab5.getDate()); 
cabinetmedical cabinet=new cabinetmedical();
String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton5.getText()+"' and date_rdv='"+date+"'";
System.out.println(req_sql);
ResultSet rs_medical = cabinet.statement.executeQuery(req_sql); 

  while (rs_medical.next()) { 
 if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
 if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
 if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
 if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
 if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
  if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
}
 } catch (SQLException ex) {
ex.printStackTrace();
}
 afficher(box1,box2,box3,box4,box5,box6);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
        try {
DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
 String date= df.format(cab5.getDate()); 
cabinetmedical cabinet=new cabinetmedical();
String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton7.getText()+"' and date_rdv='"+date+"'";
System.out.println(req_sql);
ResultSet rs_medical = cabinet.statement.executeQuery(req_sql); 
 while (rs_medical.next()) { 
 if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
 if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
 if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
 if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
 if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
  if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
}
 } catch (SQLException ex) {
ex.printStackTrace();
}
 afficher(box1,box2,box3,box4,box5,box6);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
        try {
DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
 String date= df.format(cab5.getDate()); 
cabinetmedical cabinet=new cabinetmedical();
String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton8.getText()+"' and date_rdv='"+date+"'";
System.out.println(req_sql);
ResultSet rs_medical = cabinet.statement.executeQuery(req_sql); 

  while (rs_medical.next()) { 
 if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
 if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
 if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
 if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
 if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
  if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
}
 } catch (SQLException ex) {
ex.printStackTrace();
}
 afficher(box1,box2,box3,box4,box5,box6);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
 int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
 System.out.println(jButton9.getText());
        try {
DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
 String date= df.format(cab5.getDate()); 
cabinetmedical cabinet=new cabinetmedical();
String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton9.getText()+"' and date_rdv='"+date+"'";
System.out.println(req_sql);
ResultSet rs_medical = cabinet.statement.executeQuery(req_sql); 

  while (rs_medical.next()) { 
 if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
 if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
 if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
 if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
 if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
  if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
}
 } catch (SQLException ex) {
ex.printStackTrace();
}
 afficher(box1,box2,box3,box4,box5,box6);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
        try {
DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
 String date= df.format(cab5.getDate()); 
cabinetmedical cabinet=new cabinetmedical();
String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton10.getText()+"' and date_rdv='"+date+"'";
System.out.println(req_sql);
ResultSet rs_medical = cabinet.statement.executeQuery(req_sql); 

  while (rs_medical.next()) { 
 if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
 if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
 if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
 if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
 if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
  if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
}
 } catch (SQLException ex) {
ex.printStackTrace();
}
 afficher(box1,box2,box3,box4,box5,box6);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void cab5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cab5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cab5FocusGained

    private void cab5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cab5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cab5FocusLost

    private void cab5VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cab5VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cab5VetoableChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(afficher_rdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(afficher_rdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(afficher_rdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(afficher_rdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                afficher_rdv dialog = new afficher_rdv(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bdddox4;
    private javax.swing.JPanel bodddx3;
    private javax.swing.JLabel box1;
    private javax.swing.JLabel box2;
    private javax.swing.JLabel box3;
    private javax.swing.JLabel box4;
    private javax.swing.JLabel box5;
    private javax.swing.JLabel box6;
    private com.toedter.calendar.JDateChooser cab5;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
void afficher(int a,int b,int c,int d,int e,int f)
{
      if(a==1){
       ImageIcon imageaff= new ImageIcon("dsl1.jpg");
       box1.setIcon(imageaff);
        box1.setText("");
       box1.repaint();      
  } 
  else
  {
      ImageIcon imageaff= new ImageIcon("box1.jpg");
       box1.setIcon(imageaff);
        box1.setText("");
       box1.repaint();   
  }
    if(b==1){
       ImageIcon imageaff= new ImageIcon("dsl2.jpg");
      box2.setIcon(imageaff);
       box2.setText("");
     box2.repaint();      
  }
      else
  {
      ImageIcon imageaff= new ImageIcon("box2.jpg");
       box2.setIcon(imageaff);
        box2.setText("");
       box2.repaint();   
  }
      if(c==1){
       ImageIcon imageaff= new ImageIcon("dsl1.jpg");
       box3.setIcon(imageaff);
      box3.setText("");
   box3.repaint();      
  }
            else
  {
      ImageIcon imageaff= new ImageIcon("box3.jpg");
       box3.setIcon(imageaff);
        box3.setText("");
       box3.repaint();   
  }
        if(d==1){
       ImageIcon imageaff= new ImageIcon("dsl1.jpg");
       box4.setIcon(imageaff);
        box4.setText("");
      box4.repaint();      
  }
              else
  {
      ImageIcon imageaff= new ImageIcon("box4.jpg");
      box4.setIcon(imageaff);
        box4.setText("");
      box4.repaint();   
  }
          if(e==1){
       ImageIcon imageaff= new ImageIcon("dsl2.jpg");
         box5.setIcon(imageaff);
        box5.setText("");
      box5.repaint();    
  }
                        else
  {
      ImageIcon imageaff= new ImageIcon("box5.jpg");
          box5.setIcon(imageaff);
        box5.setText("");
      box5.repaint();    
  }
                    if(f==1){
     ImageIcon imageaff= new ImageIcon("dsl2.jpg");
         box6.setIcon(imageaff);
        box6.setText("");
      box6.repaint();      
  }
                        else
  {
      ImageIcon imageaff= new ImageIcon("box6.jpg");
       box6.setIcon(imageaff);
        box6.setText("");
      box6.repaint();    
  }
}
}
