/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_du_cabinet_medical;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class ajouter_RDV extends javax.swing.JDialog {
String timeaj="";
    /**
     * Creates new form ajouter_RDV
     */
    public ajouter_RDV(java.awt.Frame parent, boolean modal,String a) {
        super(parent, modal);
        initComponents();
            this.getContentPane().setBackground(Color.decode("#000"));
        
     jLabel16.setText(a);
     Date da=null;
   try {
 DateFormat df = new SimpleDateFormat("dd-MMMM-yyyy"); 
cabinetmedical cabinet=new cabinetmedical();
String req_sql = "SELECT * FROM patient where cin= '"+a+"'";
ResultSet rs_medical = cabinet.statement.executeQuery(req_sql);
 rs_medical.next();
 
 jLabel9.setText(rs_medical.getString("nom"));
jLabel11.setText(rs_medical.getString("prenom"));
jLabel12.setText(rs_medical.getString("sexe"));
  da=rs_medical.getDate("date_naissance");
} catch (SQLException ex) {
ex.printStackTrace();
}
   
   DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
String date_niss= df.format(da); 

Calendar cal = new GregorianCalendar();  
Date d1 = null;
Date d2 = null;
try {
d1 = df.parse(date_niss);
d2 = df.parse(df.format(cal.getTime()));
//in milliseconds
long diff = d2.getTime() - d1.getTime();
long diffDays = diff / (24 * 60 * 60 * 1000);
long dfda=diffDays/ 365;
System.out.print(dfda + "ann, "); 
jLabel18.setText(""+dfda);
} catch (Exception e) {
e.printStackTrace();
}      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        box1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        box2 = new javax.swing.JLabel();
        bodddx3 = new javax.swing.JPanel();
        box3 = new javax.swing.JLabel();
        bdddox4 = new javax.swing.JPanel();
        box4 = new javax.swing.JLabel();
        b1 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        b3 = new javax.swing.JRadioButton();
        b4 = new javax.swing.JRadioButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        box5 = new javax.swing.JLabel();
        b5 = new javax.swing.JRadioButton();
        jPanel17 = new javax.swing.JPanel();
        box6 = new javax.swing.JLabel();
        b6 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cab5 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1178, 710));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajouter de Rendez Vous");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 0, 498, 56);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));

        box1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/box1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        box2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/box2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        box3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/box3.jpg"))); // NOI18N

        javax.swing.GroupLayout bodddx3Layout = new javax.swing.GroupLayout(bodddx3);
        bodddx3.setLayout(bodddx3Layout);
        bodddx3Layout.setHorizontalGroup(
            bodddx3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodddx3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodddx3Layout.setVerticalGroup(
            bodddx3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodddx3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        box4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/box4.jpg"))); // NOI18N

        javax.swing.GroupLayout bdddox4Layout = new javax.swing.GroupLayout(bdddox4);
        bdddox4.setLayout(bdddox4Layout);
        bdddox4Layout.setHorizontalGroup(
            bdddox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bdddox4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bdddox4Layout.setVerticalGroup(
            bdddox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bdddox4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        b1.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(b1);
        b1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        b1.setText("Box 1");

        b2.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(b2);
        b2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        b2.setText("Reeducation 2");

        b3.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(b3);
        b3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        b3.setText("Box 2");

        b4.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(b4);
        b4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        b4.setText("Table Bobath");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bodddx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bdddox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(b1)
                .addGap(128, 128, 128)
                .addComponent(b2)
                .addGap(108, 108, 108)
                .addComponent(b3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b4)
                .addGap(72, 72, 72))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bodddx3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdddox4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b2)
                    .addComponent(b3)
                    .addComponent(b4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));

        box5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/box5.jpg"))); // NOI18N

        buttonGroup2.add(b5);
        b5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        b5.setText("Table bébé");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(box5))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(b5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b5))
        );

        box6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/box6.jpg"))); // NOI18N

        buttonGroup2.add(b6);
        b6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        b6.setText("Table 4 plan");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b6)
                .addGap(81, 81, 81))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b6)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nom:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Prénom:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Sexe:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Age:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("jLabel11");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("jLabel12");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("jLabel18");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel18))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(190, 90, 975, 600);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date  :");

        cab5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cab5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cab5FocusLost(evt);
            }
        });
        cab5.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cab5VetoableChange(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CIN :");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Date  :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(cab5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cab5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(190, 60, 975, 33);

        jButton3.setBackground(new java.awt.Color(102, 153, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("8 ==> 9");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 153, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("9 ==> 10");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 153, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setText("11 ==> 12");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 153, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setText("10 ==> 11");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(102, 153, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton7.setText("17 ==> 18");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 153, 255));
        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton8.setText("16 ==> 17");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 153, 255));
        jButton9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton9.setText("15 ==> 16");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(102, 153, 255));
        jButton10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton10.setText("14 ==> 15");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel14.setText("Heure sélectionné  :");

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel17.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(8, 73, 178, 650);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/arriereplan.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 1180, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cab5VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cab5VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cab5VetoableChange

    private void cab5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cab5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cab5FocusLost

    private void cab5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cab5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cab5FocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
       timeaj=jButton3.getText();
       jLabel17.setText(timeaj);
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String date= df.format(cab5.getDate());
            cabinetmedical cabinet=new cabinetmedical();
            String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton3.getText()+"' and date_rdv='"+date+"'";
            System.out.println(req_sql);
            ResultSet rs_medical = cabinet.statement.executeQuery(req_sql);

            while (rs_medical.next()) {
                if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
                if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
                if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
                if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
                if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
                if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        afficher(box1,box2,box3,box4,box5,box6);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           timeaj=jButton4.getText();
             jLabel17.setText(timeaj);
        int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String date= df.format(cab5.getDate());
            cabinetmedical cabinet=new cabinetmedical();
            String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton4.getText()+"' and date_rdv='"+date+"'";
            System.out.println(req_sql);
            ResultSet rs_medical = cabinet.statement.executeQuery(req_sql);

            while (rs_medical.next()) {
                if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
                if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
                if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
                if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
                if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
                if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        afficher(box1,box2,box3,box4,box5,box6);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
             timeaj=jButton5.getText();
               jLabel17.setText(timeaj);
        int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String date= df.format(cab5.getDate());
            cabinetmedical cabinet=new cabinetmedical();
            String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton5.getText()+"' and date_rdv='"+date+"'";
            System.out.println(req_sql);
            ResultSet rs_medical = cabinet.statement.executeQuery(req_sql);

            while (rs_medical.next()) {
                if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
                if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
                if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
                if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
                if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
                if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        afficher(box1,box2,box3,box4,box5,box6);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
             timeaj=jButton6.getText();
               jLabel17.setText(timeaj);
        int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String date= df.format(cab5.getDate());
            cabinetmedical cabinet=new cabinetmedical();
            String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton5.getText()+"' and date_rdv='"+date+"'";
            System.out.println(req_sql);
            ResultSet rs_medical = cabinet.statement.executeQuery(req_sql);

            while (rs_medical.next()) {
                if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
                if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
                if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
                if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
                if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
                if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        afficher(box1,box2,box3,box4,box5,box6);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
              timeaj=jButton7.getText();
                jLabel17.setText(timeaj);
        int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String date= df.format(cab5.getDate());
            cabinetmedical cabinet=new cabinetmedical();
            String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton7.getText()+"' and date_rdv='"+date+"'";
            System.out.println(req_sql);
            ResultSet rs_medical = cabinet.statement.executeQuery(req_sql);
            while (rs_medical.next()) {
                if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
                if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
                if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
                if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
                if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
                if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        afficher(box1,box2,box3,box4,box5,box6);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
             timeaj=jButton8.getText();
               jLabel17.setText(timeaj);
        int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String date= df.format(cab5.getDate());
            cabinetmedical cabinet=new cabinetmedical();
            String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton8.getText()+"' and date_rdv='"+date+"'";
            System.out.println(req_sql);
            ResultSet rs_medical = cabinet.statement.executeQuery(req_sql);

            while (rs_medical.next()) {
                if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
                if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
                if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
                if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
                if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
                if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        afficher(box1,box2,box3,box4,box5,box6);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
             timeaj=jButton9.getText();
               jLabel17.setText(timeaj);
        System.out.println(jButton9.getText());
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String date= df.format(cab5.getDate());
            cabinetmedical cabinet=new cabinetmedical();
            String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton9.getText()+"' and date_rdv='"+date+"'";
            System.out.println(req_sql);
            ResultSet rs_medical = cabinet.statement.executeQuery(req_sql);

            while (rs_medical.next()) {
                if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
                if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
                if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
                if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
                if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
                if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        afficher(box1,box2,box3,box4,box5,box6);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
             timeaj=jButton10.getText();
               jLabel17.setText(timeaj);
        int box1=0,box2=0,box3=0,box4=0,box5=0,box6=0;
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String date= df.format(cab5.getDate());
            cabinetmedical cabinet=new cabinetmedical();
            String req_sql = "SELECT * FROM Rendez_Vous where heur_rdv='"+jButton10.getText()+"' and date_rdv='"+date+"'";
            System.out.println(req_sql);
            ResultSet rs_medical = cabinet.statement.executeQuery(req_sql);

            while (rs_medical.next()) {
                if(rs_medical.getString("tab").toString().equals("Box 1"))box1=1;
                if(rs_medical.getString("tab").toString().equals("Reeducation 2"))box2=1;
                if(rs_medical.getString("tab").toString().equals("Box 2"))box3=1;
                if(rs_medical.getString("tab").toString().equals("Table Bobath"))box4=1;
                if(rs_medical.getString("tab").toString().equals("Table bebe"))box5=1;
                if(rs_medical.getString("tab").toString().equals("Table 4 plan"))box6=1;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        afficher(box1,box2,box3,box4,box5,box6);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 DateFormat formatJJMMAAAA = new SimpleDateFormat("yyyy-MM-dd"); 
Calendar cal1 = new GregorianCalendar(); 
cal1.add (Calendar.DATE, -1);
  Date date1=cal1.getTime();
        String tab="";
if(b1.isSelected()) tab="Box 1" ;
if(b2.isSelected()) tab="Reeducation 2" ;
  if(b3.isSelected()) tab="Box 2" ;
  if(b4.isSelected()) tab="Table Bobath" ;
  if(b5.isSelected()) tab="Table bebe";
  if(b6.isSelected()) tab="Table 4 plan";
        
 Date date2=cab5.getDate(); 
 if(date1.after(date2)||date2==null){
 JOptionPane.showMessageDialog(null, "Vérifier la date de RDV !");
 cab5.setDate(null);
  }
 
  else
 {
        
        

 DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
 
String d= df.format(cab5.getDate());
 if(tab.equals("")||timeaj.equals(""))JOptionPane.showMessageDialog(null,"Un erreur est detecte veuillez Remplir les champs vides.","Erreur !",JOptionPane.ERROR_MESSAGE);
 else
 {
try {
cabinetmedical medical= new cabinetmedical();
 medical.medical_update("INSERT INTO `rendez_vous` (`num_rendezvous`, `cin_patient`, `date_rdv`, `heur_rdv`, `tab`, `sexe`)"
         + " VALUES (NULL, '"+jLabel16.getText()+"', '"+d+"', '"+timeaj+"', '"+tab+"', '"+jLabel12.getText()+"');" +
"");
JOptionPane.showMessageDialog(null ," enregistrement effectué");
       dispose();
} catch (SQLException e) {  }
   
 }  }  
  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouter_RDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouter_RDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouter_RDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouter_RDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ajouter_RDV dialog = new ajouter_RDV(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    private javax.swing.JRadioButton b5;
    private javax.swing.JRadioButton b6;
    private javax.swing.JPanel bdddox4;
    private javax.swing.JPanel bodddx3;
    private javax.swing.JLabel box1;
    private javax.swing.JLabel box2;
    private javax.swing.JLabel box3;
    private javax.swing.JLabel box4;
    private javax.swing.JLabel box5;
    private javax.swing.JLabel box6;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser cab5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
void afficher(int a,int b,int c,int d,int e,int f)
{
      if(a==1){
       ImageIcon imageaff= new ImageIcon("dsl1.jpg");
       box1.setIcon(imageaff);
        box1.setText("");
       box1.repaint();    
             b1.setEnabled(false);
      
  } 
  else
  {
      ImageIcon imageaff= new ImageIcon("box1.jpg");
       box1.setIcon(imageaff);
        box1.setText("");
       box1.repaint();   
     b1.setEnabled(true);
  }
    if(b==1){
       ImageIcon imageaff= new ImageIcon("dsl2.jpg");
      box2.setIcon(imageaff);
       box2.setText("");
     box2.repaint();
      b2.setEnabled(false);
  }
      else
  {
      ImageIcon imageaff= new ImageIcon("box2.jpg");
       box2.setIcon(imageaff);
        box2.setText("");
       box2.repaint();   
        b2.setEnabled(true);
  }
      if(c==1){
       ImageIcon imageaff= new ImageIcon("dsl1.jpg");
       box3.setIcon(imageaff);
      box3.setText("");
   box3.repaint();   
    b3.setEnabled(false);
  }
            else
  {
      ImageIcon imageaff= new ImageIcon("box3.jpg");
       box3.setIcon(imageaff);
        box3.setText("");
       box3.repaint();  
        b3.setEnabled(true);
  }
        if(d==1){
       ImageIcon imageaff= new ImageIcon("dsl1.jpg");
       box4.setIcon(imageaff);
        box4.setText("");
      box4.repaint();  
     b4.setEnabled(false);
    
  }
              else
  {
      ImageIcon imageaff= new ImageIcon("box4.jpg");
      box4.setIcon(imageaff);
        box4.setText("");
      box4.repaint(); 
        b4.setEnabled(true);
        
  }
          if(e==1){
       ImageIcon imageaff= new ImageIcon("dsl2.jpg");
         box5.setIcon(imageaff);
        box5.setText("");
      box5.repaint();   
        b5.setEnabled(false);
  }
                        else
  {
      ImageIcon imageaff= new ImageIcon("box5.jpg");
          box5.setIcon(imageaff);
        box5.setText("");
      box5.repaint();   
        b5.setEnabled(true);
  }
                    if(f==1){
     ImageIcon imageaff= new ImageIcon("dsl2.jpg");
         box6.setIcon(imageaff);
        box6.setText("");
      box6.repaint();   
            b6.setEnabled(false);
  }
                        else
  {
      ImageIcon imageaff= new ImageIcon("box6.jpg");
       box6.setIcon(imageaff);
        box6.setText("");
      box6.repaint();   
      b6.setEnabled(true);
  }
}
}

