/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_du_cabinet_medical;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Identifiant extends javax.swing.JDialog {

    /**
     * Creates new form Identifiant
     */
    public Identifiant(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        iden = new javax.swing.JLabel();
        cab14 = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Mot de Passe  :");

        iden.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        iden.setForeground(new java.awt.Color(255, 255, 255));
        iden.setText("Identifiant :");

        cab14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cab14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab14ActionPerformed(evt);
            }
        });
        cab14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cab14KeyReleased(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(79, 184, 72));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Entrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseEntered(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 60)); // NOI18N
        jLabel1.setText("Bienvenue");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/logo.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/arriereplan.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(iden, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(cab14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(iden, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(cab14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cab14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab14ActionPerformed

    private void cab14KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cab14KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cab14KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
System.out.println("kkkk"); 
 
String type="";
try{
cabinetmedical medical = new cabinetmedical();
ResultSet res1=medical.medical_select("select * from utilisateur where identifiant='"+ cab14.getText() +"' and Mot_de_Passe='" +jPasswordField1.getText() + "'");
if (res1.next()){
 System.out.println(res1.getString("type")); 
 type=res1.getString("type");
 }
} catch(Exception SQLException){ 
type="";
cab14.setText(""); 
jPasswordField1.setText(""); 
}
if(!type.equals(""))
{
    if(type.equals("Secrétaire"))
    {
Cabinet_medical_sec cabinet_medical = new Cabinet_medical_sec(null, true);
Dimension taille_ecran = Toolkit.getDefaultToolkit().getScreenSize();
//cabinet_medical.setLocation(taille_ecran.width / 2 - cabinet_medical.getWidth() / 2, taille_ecran.height / 2 -cabinet_medical.getHeight() / 2);
 cabinet_medical.setBounds(0, 0,taille_ecran.width , taille_ecran.height);
cabinet_medical.setResizable(false);
cabinet_medical.setVisible(true);  
dispose();} 
    else
           {
Cabinet_medical cabinet_medical = new Cabinet_medical(null, true);
Dimension taille_ecran = Toolkit.getDefaultToolkit().getScreenSize();
 cabinet_medical.setBounds(0, 0,taille_ecran.width , taille_ecran.height);
cabinet_medical.setResizable(false);
cabinet_medical.setVisible(true);  
dispose();} 
    } 
else
{ 
 JOptionPane.showMessageDialog(this, " verifier votre login et/ou votre mot de passe", "Erreur", JOptionPane.WARNING_MESSAGE);
cab14.setText(""); 
jPasswordField1.setText("");      
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseEntered
//System.out.println("kkkk"); 
// 
//String type="";
//try{
//cabinetmedical medical = new cabinetmedical();
//ResultSet res1=medical.medical_select("select * from utilisateur where identifiant='"+ cab14.getText() +"' and Mot_de_Passe='" +jPasswordField1.getText() + "'");
//if (res1.next()){
// System.out.println(res1.getString("type")); 
// type=res1.getString("type");
// }
//} catch(Exception SQLException){ 
//type="";
//cab14.setText(""); 
//jPasswordField1.setText(""); 
//}
//if(!type.equals(""))
//{
//    if(type.equals("Secrétaire"))
//    {
//Cabinet_medical_sec cabinet_medical = new Cabinet_medical_sec(null, true);
//Dimension taille_ecran = Toolkit.getDefaultToolkit().getScreenSize();
//cabinet_medical.setLocation(taille_ecran.width / 2 - cabinet_medical.getWidth() / 2, taille_ecran.height / 2 -cabinet_medical.getHeight() / 2);
// 
//cabinet_medical.setResizable(false);
//cabinet_medical.setVisible(true);  
//dispose();} 
//    else
//           {
//Cabinet_medical cabinet_medical = new Cabinet_medical(null, true);
//Dimension taille_ecran = Toolkit.getDefaultToolkit().getScreenSize();
//cabinet_medical.setLocation(taille_ecran.width / 2 - cabinet_medical.getWidth() / 2, taille_ecran.height / 2 -cabinet_medical.getHeight() / 2);
// 
//cabinet_medical.setResizable(false);
//cabinet_medical.setVisible(true);  
//dispose();} 
//    } 
//else
//{ 
// JOptionPane.showMessageDialog(this, " verifier votre login et/ou votre mot de passe", "Erreur", JOptionPane.WARNING_MESSAGE);
//cab14.setText(""); 
//jPasswordField1.setText("");      
//}        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1MouseEntered

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
   if (evt.getKeyCode()==KeyEvent.VK_ENTER){  
String type="";
try{
cabinetmedical medical = new cabinetmedical();
ResultSet res1=medical.medical_select("select * from utilisateur where identifiant='"+ cab14.getText() +"' and Mot_de_Passe='" +jPasswordField1.getText() + "'");
if (res1.next()){
 System.out.println(res1.getString("type")); 
 type=res1.getString("type");
 }
} catch(Exception SQLException){ 
type="";
cab14.setText(""); 
jPasswordField1.setText(""); 
}
if(!type.equals(""))
{
    if(type.equals("Secrétaire"))
    {
Cabinet_medical_sec cabinet_medical = new Cabinet_medical_sec(null, true);
Dimension taille_ecran = Toolkit.getDefaultToolkit().getScreenSize();
//cabinet_medical.setLocation(taille_ecran.width / 2 - cabinet_medical.getWidth() / 2, taille_ecran.height / 2 -cabinet_medical.getHeight() / 2);
 cabinet_medical.setBounds(0, 0,taille_ecran.width , taille_ecran.height);
cabinet_medical.setResizable(false);
cabinet_medical.setVisible(true);  
dispose();} 
    else
           {
Cabinet_medical cabinet_medical = new Cabinet_medical(null, true);
Dimension taille_ecran = Toolkit.getDefaultToolkit().getScreenSize();
 cabinet_medical.setBounds(0, 0,taille_ecran.width , taille_ecran.height);
cabinet_medical.setResizable(false);
cabinet_medical.setVisible(true);  
dispose();} 
    } 
else
{ 
 JOptionPane.showMessageDialog(this, " verifier votre login et/ou votre mot de passe", "Erreur", JOptionPane.WARNING_MESSAGE);
cab14.setText(""); 
jPasswordField1.setText("");      
}
   }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
    
 
    }//GEN-LAST:event_jPasswordField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Identifiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Identifiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Identifiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Identifiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Identifiant dialog = new Identifiant(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cab14;
    private javax.swing.JLabel iden;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
