/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_du_cabinet_medical;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class LetterdeLiaison extends javax.swing.JDialog {

    /**
     * Creates new form LetterdeLiaison
     */
    public LetterdeLiaison(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        letter();
              this.getContentPane().setBackground(Color.decode("#000"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cab34 = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lettre de Liaison");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 10, 370, 56);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 130, 708, 283);

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(100, 420, 140, 40);

        jButton1.setBackground(new java.awt.Color(79, 184, 72));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(530, 420, 140, 40);

        jButton3.setBackground(new java.awt.Color(102, 153, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Afficher");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(320, 420, 140, 40);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Numéro CIN :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(170, 80, 140, 30);

        cab34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab34ActionPerformed(evt);
            }
        });
        jPanel1.add(cab34);
        cab34.setBounds(300, 80, 150, 30);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton4.setText("Afficher tout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(630, 80, 140, 33);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton5.setText("Rechercher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(470, 80, 140, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/arriereplan.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 830, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
aj_patient_LetterdeLiaison cabinet_medical = new aj_patient_LetterdeLiaison(null, true);
Dimension taille_ecran = Toolkit.getDefaultToolkit().getScreenSize();
cabinet_medical.setLocation(taille_ecran.width / 2 - cabinet_medical.getWidth() / 2, taille_ecran.height / 2 -cabinet_medical.getHeight() / 2);
cabinet_medical.setResizable(false);
cabinet_medical.setVisible(true);
            //}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
letter();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  try {
String a=jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        aff_patient_LetterdeLiaison cabinet_medical = new aff_patient_LetterdeLiaison(null, true,a);
Dimension taille_ecran = Toolkit.getDefaultToolkit().getScreenSize();
cabinet_medical.setLocation(taille_ecran.width / 2 - cabinet_medical.getWidth() / 2, taille_ecran.height / 2 -cabinet_medical.getHeight() / 2);
cabinet_medical.setResizable(false);
cabinet_medical.setVisible(true);
} catch (Exception e) {
JOptionPane.showMessageDialog(null, "Veuillez selectionner une Letter, SVP");

}// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cab34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab34ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   letter();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     if(cab34.getText().toString().length()==0) letter();
else letter(cab34.getText().toString());    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LetterdeLiaison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LetterdeLiaison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LetterdeLiaison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LetterdeLiaison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LetterdeLiaison dialog = new LetterdeLiaison(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cab34;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
void letter()
 {
try {
 DateFormat df = new SimpleDateFormat("dd-MMMM-yyyy"); 
cabinetmedical cabinet=new cabinetmedical();
String req_sql = "SELECT * FROM letterdeliaison";
ResultSet rs_medical = cabinet.statement.executeQuery(req_sql);
 String titre [] = { "Numero Letter","Date Letter", "Docteur","Numero Rendezvous", "CIN", "Patient"};
 int indis = 0; 
rs_medical.last();
String donnee_bd[][] = new String[rs_medical.getRow()][6];
rs_medical.beforeFirst();
 while (rs_medical.next()) { 
donnee_bd[indis][0] = ""+rs_medical.getString(1);
donnee_bd[indis][1] = ""+df.format(rs_medical.getDate(2));
donnee_bd[indis][2] = ""+rs_medical.getString(3);
donnee_bd[indis][3] = ""+rs_medical.getString(4);
donnee_bd[indis][4] = ""+rs_medical.getString(5);
   cabinetmedical cabinet1=new cabinetmedical();
     ResultSet rs_medical1 = cabinet1.statement.executeQuery("SELECT * FROM patient where cin='"+rs_medical.getString(5)+"'");
     if(rs_medical1.next())donnee_bd[indis][5] = ""+rs_medical1.getString("nom")+"\t"+rs_medical1.getString("prenom");
     else donnee_bd[indis][5] = ""+rs_medical.getString(5);
     rs_medical1.close();
 indis++;
}
DefaultTableModel model = new DefaultTableModel(donnee_bd, titre );
jTable1.setModel(model);  
} catch (SQLException ex) {
ex.printStackTrace();
}
}
void letter(String a)
 {
try {
 DateFormat df = new SimpleDateFormat("dd-MMMM-yyyy"); 
cabinetmedical cabinet=new cabinetmedical();
String req_sql = "SELECT * FROM letterdeliaison where patient='"+a+"'";
ResultSet rs_medical = cabinet.statement.executeQuery(req_sql);
 String titre [] = { "Numero Letter","Date Letter", "Docteur","Numero Rendezvous", "CIN", "Patient"};
 int indis = 0; 
rs_medical.last();
String donnee_bd[][] = new String[rs_medical.getRow()][6];
rs_medical.beforeFirst();
 while (rs_medical.next()) { 
     cabinetmedical cabinet1=new cabinetmedical();
     ResultSet rs_medical1 = cabinet1.statement.executeQuery("SELECT * FROM patient where cin='"+rs_medical.getString(5)+"'");
     if(rs_medical1.next())donnee_bd[indis][5] = ""+rs_medical1.getString("nom")+"\t"+rs_medical1.getString("prenom");
     else donnee_bd[indis][5] = ""+rs_medical.getString(5);
donnee_bd[indis][0] = ""+rs_medical.getString(1);
donnee_bd[indis][1] = ""+df.format(rs_medical.getDate(2));
donnee_bd[indis][2] = ""+rs_medical.getString(3);
donnee_bd[indis][3] = ""+rs_medical.getString(4); 
donnee_bd[indis][4] = ""+rs_medical.getString(5); 
 indis++;
 rs_medical1.close();
}
DefaultTableModel model = new DefaultTableModel(donnee_bd, titre );
jTable1.setModel(model);  
} catch (SQLException ex) {
ex.printStackTrace();
}
}
//INSERT INTO `cabinetmedical`.`letterdeliaison` (`num_letter`, `date_letter`, `docteur`, `numero_rendezvous`, `patient`, `lettere`) VALUES (NULL, '2015-04-08', '3', '33', '333', 'DDDD');
}
