/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_du_cabinet_medical;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class utilisateur extends javax.swing.JDialog {

    /**
     * Creates new form utilisateur
     */
    public utilisateur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
            this.getContentPane().setBackground(Color.decode("#000"));
            utilisateur();
         jTabbedPane1.setEnabledAt(2, false);
jTabbedPane1.setEnabledAt(3,false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cab1 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cab12 = new javax.swing.JTextArea();
        cab3 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cab2 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        cab11 = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cab10 = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cab14 = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cab4 = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cab15 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cab17 = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        cab18 = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        cab19 = new javax.swing.JFormattedTextField();
        jLabel29 = new javax.swing.JLabel();
        cab20 = new javax.swing.JFormattedTextField();
        jLabel30 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cab25 = new javax.swing.JFormattedTextField();
        cab37 = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        cab23 = new javax.swing.JFormattedTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cab26 = new javax.swing.JTextArea();
        cab27 = new javax.swing.JFormattedTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        cab28 = new javax.swing.JFormattedTextField();
        jLabel40 = new javax.swing.JLabel();
        cab29 = new javax.swing.JFormattedTextField();
        jLabel41 = new javax.swing.JLabel();
        cab30 = new javax.swing.JFormattedTextField();
        jLabel42 = new javax.swing.JLabel();
        cab31 = new javax.swing.JFormattedTextField();
        jLabel43 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        cab35 = new javax.swing.JFormattedTextField();
        cab36 = new javax.swing.JFormattedTextField();
        jLabel47 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(47, 46, 48));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jLabel48.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("   Recherche d'utilisateur");
        jPanel2.add(jLabel48);
        jLabel48.setBounds(160, 10, 560, 50);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Type  :");

        jRadioButton7.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Kinésithérapeute");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("Secrétaire");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton7.setText("Afficher Tout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton7)
                .addGap(81, 81, 81)
                .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8);
        jPanel8.setBounds(20, 70, 750, 60);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable1);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(20, 150, 750, 240);

        jButton9.setBackground(new java.awt.Color(255, 0, 51));
        jButton9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton9.setText("Annuler");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(350, 400, 140, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/arriereplan.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 820, 450);

        jTabbedPane1.addTab("Recherche Utilisateur", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ajouter Utilisateur");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(260, 20, 410, 60);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Numéro CIN :");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(30, 101, 140, 30);

        cab1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab1ActionPerformed(evt);
            }
        });
        cab1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cab1KeyReleased(evt);
            }
        });
        jPanel3.add(cab1);
        cab1.setBounds(220, 101, 150, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Adresse :");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(410, 271, 120, 30);

        cab12.setColumns(20);
        cab12.setRows(5);
        jScrollPane1.setViewportView(cab12);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(550, 270, 260, 120);

        cab3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab3ActionPerformed(evt);
            }
        });
        jPanel3.add(cab3);
        cab3.setBounds(220, 181, 150, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Prénom :");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(30, 181, 120, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nom :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(30, 141, 120, 30);

        cab2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab2ActionPerformed(evt);
            }
        });
        jPanel3.add(cab2);
        cab2.setBounds(220, 141, 150, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Numéro GSM :");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(410, 221, 180, 30);

        cab11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cab11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab11ActionPerformed(evt);
            }
        });
        cab11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cab11KeyReleased(evt);
            }
        });
        jPanel3.add(cab11);
        cab11.setBounds(550, 220, 150, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Sexe :");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(30, 230, 130, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Type :");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(30, 310, 180, 30);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Homme");
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(220, 221, 150, 33);

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jRadioButton2.setText("Femme");
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(220, 251, 150, 33);

        jButton1.setBackground(new java.awt.Color(79, 184, 72));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(670, 400, 140, 40);

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(480, 400, 140, 40);

        cab10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cab10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab10ActionPerformed(evt);
            }
        });
        cab10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cab10KeyReleased(evt);
            }
        });
        jPanel3.add(cab10);
        cab10.setBounds(550, 160, 150, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Mot de Passe  :");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(410, 160, 180, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Identifiant :");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(410, 100, 180, 30);

        cab14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cab14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab14ActionPerformed(evt);
            }
        });
        cab14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cab14KeyReleased(evt);
            }
        });
        jPanel3.add(cab14);
        cab14.setBounds(550, 100, 150, 30);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kinésithérapeute", "Secrétaire" }));
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(220, 310, 150, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/arriereplan.jpg"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 820, 450);

        jTabbedPane1.addTab("Ajouter Utilisateur", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Modifier Utilisateur");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(200, 20, 450, 40);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Numéro CIN :");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(30, 101, 140, 30);

        cab4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cab4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab4ActionPerformed(evt);
            }
        });
        cab4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cab4KeyReleased(evt);
            }
        });
        jPanel6.add(cab4);
        cab4.setBounds(220, 101, 150, 30);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Adresse :");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(410, 271, 120, 30);

        cab15.setColumns(20);
        cab15.setRows(5);
        jScrollPane2.setViewportView(cab15);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(540, 270, 260, 120);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Prénom :");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(30, 200, 120, 30);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Nom :");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(30, 150, 120, 30);

        cab17.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cab17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab17ActionPerformed(evt);
            }
        });
        jPanel6.add(cab17);
        cab17.setBounds(220, 250, 150, 30);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Numéro GSM :");
        jPanel6.add(jLabel27);
        jLabel27.setBounds(410, 221, 180, 30);

        cab18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab18ActionPerformed(evt);
            }
        });
        cab18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cab18KeyReleased(evt);
            }
        });
        jPanel6.add(cab18);
        cab18.setBounds(540, 220, 150, 30);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Identifiant :");
        jPanel6.add(jLabel28);
        jLabel28.setBounds(410, 100, 180, 30);

        cab19.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cab19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab19ActionPerformed(evt);
            }
        });
        cab19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cab19KeyReleased(evt);
            }
        });
        jPanel6.add(cab19);
        cab19.setBounds(540, 100, 150, 30);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Sexe :");
        jPanel6.add(jLabel29);
        jLabel29.setBounds(30, 250, 130, 30);

        cab20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab20ActionPerformed(evt);
            }
        });
        cab20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cab20KeyReleased(evt);
            }
        });
        jPanel6.add(cab20);
        cab20.setBounds(540, 160, 150, 30);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Mot de Passe  :");
        jPanel6.add(jLabel30);
        jLabel30.setBounds(410, 160, 180, 30);

        jButton3.setBackground(new java.awt.Color(79, 184, 72));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);
        jButton3.setBounds(660, 400, 140, 40);

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton4.setText("Annuler");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);
        jButton4.setBounds(470, 400, 140, 40);

        cab25.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cab25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab25ActionPerformed(evt);
            }
        });
        jPanel6.add(cab25);
        cab25.setBounds(220, 200, 150, 30);

        cab37.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cab37.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab37ActionPerformed(evt);
            }
        });
        jPanel6.add(cab37);
        cab37.setBounds(220, 150, 150, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Type :");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(30, 310, 180, 30);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kinésithérapeute", "Secrétaire" }));
        jPanel6.add(jComboBox2);
        jComboBox2.setBounds(220, 310, 150, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/arriereplan.jpg"))); // NOI18N
        jPanel6.add(jLabel6);
        jLabel6.setBounds(0, 0, 820, 450);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Modifier Utilisateur", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Supprimer Utilisateur");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(210, 20, 490, 50);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Numéro CIN :");
        jPanel7.add(jLabel34);
        jLabel34.setBounds(30, 101, 140, 30);

        cab23.setEditable(false);
        cab23.setBackground(new java.awt.Color(255, 255, 255));
        cab23.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cab23.setEnabled(false);
        cab23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab23ActionPerformed(evt);
            }
        });
        cab23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cab23KeyReleased(evt);
            }
        });
        jPanel7.add(cab23);
        cab23.setBounds(220, 101, 150, 30);

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Type :");
        jPanel7.add(jLabel36);
        jLabel36.setBounds(30, 300, 180, 30);

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Adresse :");
        jPanel7.add(jLabel37);
        jLabel37.setBounds(410, 271, 120, 30);

        cab26.setEditable(false);
        cab26.setColumns(20);
        cab26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cab26.setRows(5);
        cab26.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cab26.setEnabled(false);
        jScrollPane3.setViewportView(cab26);

        jPanel7.add(jScrollPane3);
        jScrollPane3.setBounds(550, 270, 260, 120);

        cab27.setEditable(false);
        cab27.setBackground(new java.awt.Color(255, 255, 255));
        cab27.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cab27.setEnabled(false);
        cab27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab27ActionPerformed(evt);
            }
        });
        jPanel7.add(cab27);
        cab27.setBounds(220, 300, 150, 30);

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Prénom :");
        jPanel7.add(jLabel38);
        jLabel38.setBounds(30, 200, 120, 30);

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Nom :");
        jPanel7.add(jLabel39);
        jLabel39.setBounds(30, 150, 120, 30);

        cab28.setEditable(false);
        cab28.setBackground(new java.awt.Color(255, 255, 255));
        cab28.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cab28.setEnabled(false);
        cab28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab28ActionPerformed(evt);
            }
        });
        jPanel7.add(cab28);
        cab28.setBounds(220, 150, 150, 30);

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Numéro GS :");
        jPanel7.add(jLabel40);
        jLabel40.setBounds(410, 210, 180, 30);

        cab29.setEditable(false);
        cab29.setBackground(new java.awt.Color(255, 255, 255));
        cab29.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cab29.setEnabled(false);
        cab29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab29ActionPerformed(evt);
            }
        });
        cab29.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cab29KeyReleased(evt);
            }
        });
        jPanel7.add(cab29);
        cab29.setBounds(550, 210, 150, 30);

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Identifiant :");
        jPanel7.add(jLabel41);
        jLabel41.setBounds(410, 91, 180, 30);

        cab30.setEditable(false);
        cab30.setBackground(new java.awt.Color(255, 255, 255));
        cab30.setForeground(new java.awt.Color(255, 255, 255));
        cab30.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cab30.setEnabled(false);
        cab30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab30ActionPerformed(evt);
            }
        });
        cab30.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cab30KeyReleased(evt);
            }
        });
        jPanel7.add(cab30);
        cab30.setBounds(550, 90, 150, 30);

        jLabel42.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Sexe :");
        jPanel7.add(jLabel42);
        jLabel42.setBounds(30, 250, 130, 30);

        cab31.setEditable(false);
        cab31.setBackground(new java.awt.Color(255, 255, 255));
        cab31.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cab31.setEnabled(false);
        cab31.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab31ActionPerformed(evt);
            }
        });
        cab31.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cab31KeyReleased(evt);
            }
        });
        jPanel7.add(cab31);
        cab31.setBounds(550, 150, 150, 30);

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Mot de Passe  :");
        jPanel7.add(jLabel43);
        jLabel43.setBounds(410, 150, 180, 30);

        jButton5.setBackground(new java.awt.Color(79, 184, 72));
        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setText("Supprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5);
        jButton5.setBounds(670, 400, 140, 40);

        jButton6.setBackground(new java.awt.Color(255, 0, 51));
        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setText("Annuler");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6);
        jButton6.setBounds(480, 400, 140, 40);

        cab35.setEditable(false);
        cab35.setBackground(new java.awt.Color(255, 255, 255));
        cab35.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cab35.setEnabled(false);
        cab35.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab35ActionPerformed(evt);
            }
        });
        jPanel7.add(cab35);
        cab35.setBounds(220, 200, 150, 30);

        cab36.setEditable(false);
        cab36.setBackground(new java.awt.Color(255, 255, 255));
        cab36.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cab36.setEnabled(false);
        cab36.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cab36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cab36ActionPerformed(evt);
            }
        });
        jPanel7.add(cab36);
        cab36.setBounds(220, 250, 150, 30);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cabinet/arriereplan.jpg"))); // NOI18N
        jPanel7.add(jLabel47);
        jLabel47.setBounds(1, 0, 820, 450);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Supprimer Utilisateur", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3,false);
         utilisateur_type("Kinésithérapeute");
        jRadioButton7.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3,false);
        utilisateur_type("Secretaire");
        jRadioButton8.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3,false);
       utilisateur();// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setEnabledAt(3,true);// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void cab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab4ActionPerformed

    private void cab4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cab4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cab4KeyReleased

    private void cab17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab17ActionPerformed

    private void cab18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab18ActionPerformed

    private void cab18KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cab18KeyReleased
        String ch="";
        if (!cab18.getText().matches("[0-9]*")||cab18.getText().toString().length()>8) {
            JOptionPane.showMessageDialog(null,"Une erreur est détecté veuillez vérifier la saisi du champ GSM.","Erreur !",JOptionPane.ERROR_MESSAGE);
            for(int i=0;i<cab18.getText().length()-1;i++)
            ch=ch+cab18.getText().charAt(i);
            cab18 .setText(ch);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_cab18KeyReleased

    private void cab19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab19ActionPerformed

    private void cab19KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cab19KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cab19KeyReleased

    private void cab20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab20ActionPerformed

    private void cab20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cab20KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cab20KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if(cab15.getText().equals("") ||cab18.getText().equals("") || cab20.getText().equals("") ||cab19.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Un erreur est detecte veuillez Remplir les champs vides.","Erreur !",JOptionPane.ERROR_MESSAGE);
        } 
        else if (! cab18.getText().matches("[0-9]*")||!(cab18.getText().length()==8)) {
            JOptionPane.showMessageDialog(null,"Un erreur est detecte veuillez verifier la saisi du Numéro GSM.","Erreur !",JOptionPane.ERROR_MESSAGE);
            cab18.setText("");
        } 
        else
        {
            try {
                cabinetmedical medical= new cabinetmedical();
           medical.medical_update("UPDATE `utilisateur` SET  `identifiant` =  '"+ cab19.getText() +"', `Mot_de_Passe` =  '"+ cab20.getText() +"', "
                        + "`gsm` =  "+ cab18.getText() +", `adresse` =  '"+ cab15.getText() +"',type ='"+jComboBox1.getSelectedItem()+"' WHERE `cin` =  '"+ cab4.getText() +"'");
                JOptionPane.showMessageDialog(null ," enregistrement effectué");
             utilisateur();
                jTabbedPane1.setSelectedIndex(0);
                jTabbedPane1.setEnabledAt(2, false);
                jTabbedPane1.setEnabledAt(3,false);

            } catch (SQLException e) {
                System.out.print(e);
            } }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3,false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cab25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab25ActionPerformed

    private void cab37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab37ActionPerformed

    private void cab23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab23ActionPerformed

    private void cab23KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cab23KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cab23KeyReleased

    private void cab27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab27ActionPerformed

    private void cab28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab28ActionPerformed

    private void cab29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab29ActionPerformed

    private void cab29KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cab29KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cab29KeyReleased

    private void cab30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab30ActionPerformed

    private void cab30KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cab30KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cab30KeyReleased

    private void cab31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab31ActionPerformed

    private void cab31KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cab31KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cab31KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "Supprimer l'enregistrement", "Confirmation", JOptionPane.OK_CANCEL_OPTION);
        System.out.println(n);
        if (n == 0) {
            try {
                cabinetmedical medical= new cabinetmedical();
                String  req_sql="delete from utilisateur where cin='"+ jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "'";
                medical.medical_update(req_sql);
                JOptionPane.showMessageDialog(null ,"Enregistrement effectué");
                jTabbedPane1.setSelectedIndex(0);
                jTabbedPane1.setEnabledAt(2, false);
                jTabbedPane1.setEnabledAt(3,false);

              utilisateur();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3,false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cab35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab35ActionPerformed

    private void cab36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab36ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        if  (jTabbedPane1.getSelectedIndex()>1)
        {try {
            cabinetmedical medical= new cabinetmedical();
            ResultSet rers = medical.medical_select("select * from utilisateur where cin='" + jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "'");
            int exis = 0;
            if(rers.next())  {
                // `utilisateur` (`cin`, `nom`, `prenom`, `sexe`, `type`, `identifiant`, `Mot_de_Passe`,`gsm`, `adresse`)   
                cab4.setText(rers.getString(1));
                cab37.setText(rers.getString(2));
                cab25.setText(rers.getString(3));
                cab17.setText(rers.getString(4));
                cab19.setText(rers.getString(6));
                cab20.setText(rers.getString(7));
                cab18.setText(rers.getString(8));
                cab15.setText(rers.getString(9));  
                 cab23.setText(rers.getString(1));
                cab28.setText(rers.getString(2));
                cab35.setText(rers.getString(3));
                cab36.setText(rers.getString(4));
                    cab27.setText(rers.getString(5));
                cab30.setText(rers.getString(6));
                cab31.setText(rers.getString(7));
                cab29.setText(rers.getString(8));
                cab26.setText(rers.getString(9));                
 
  }
            } catch (SQLException e) { }

        }// TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cab1.setText("")  ;
        cab2.setText("")  ;
        cab3.setText("")  ;
        cab4.setText("")  ;
         
        cab10.setText("")  ;
        cab11.setText("")  ;
        cab12.setText("")  ;
        jTabbedPane1.setSelectedIndex(0);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3,false); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ch_sexe="";
        if(jRadioButton1.isSelected())ch_sexe="Homme";
        else
        ch_sexe="Femme";
        if( cab1.getText().equals("") ||cab2.getText().equals("") || cab3.getText().equals("") ||cab14.getText().equals("") ||cab10.getText().equals("")||cab11.getText().equals("")||cab12.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Un erreur est detecte veuillez Remplir les champs vides.","Erreur !",JOptionPane.ERROR_MESSAGE);
            } 
        else if (! cab1.getText().matches("[0-9]*")||!(cab1.getText().length()==8)) {
            JOptionPane.showMessageDialog(null,"Un erreur est detecte veuillez verifier la saisi du champ cin","Erreur !",JOptionPane.ERROR_MESSAGE);
            cab1.setText("");
            } 
        else if (! cab11.getText().matches("[0-9]*")||!(cab11.getText().length()==8)) {
            JOptionPane.showMessageDialog(null,"Un erreur est detecte veuillez verifier la saisi du Numéro GSM.","Erreur !",JOptionPane.ERROR_MESSAGE);
            cab11.setText("");
            } 
        else
        {
            try {
                cabinetmedical medical= new cabinetmedical();
                ResultSet rers = medical.medical_select("select * from patient where cin='" + cab1.getText() + "'");
                int exis = 0;
                if(rers.next())  {
                    exis = 1;
                }
                if (exis == 0) {

medical.medical_update("INSERT INTO `utilisateur` (`cin`, `nom`, `prenom`, `sexe`, `type`, `identifiant`, `Mot_de_Passe`,`gsm`, `adresse`) VALUES " +
"('"+cab1.getText()+"', '"+cab2.getText()+"', '"+cab3.getText()+"', '"+ch_sexe+"', '"+jComboBox1.getSelectedItem()+"','"+ cab14.getText()+"','"+ cab10.getText()+"', "+cab11.getText()
+",'"+cab12.getText()+"')");
JOptionPane.showMessageDialog(null ," enregistrement effectué");
                     utilisateur();
                    jTabbedPane1.setSelectedIndex(0);
                    jTabbedPane1.setEnabledAt(2, false);
                    jTabbedPane1.setEnabledAt(3,false);
                    cab1.setText("")  ;
                    cab2.setText("")  ;
                    cab3.setText("")  ;
                    cab4.setText("")  ; 
                    cab10.setText("")  ;
                    cab11.setText("")  ;
                    cab12.setText("")  ;

                }
                if (exis == 1) {
                    JOptionPane.showMessageDialog(null, "Enregistrement existe deja");
                }
            } catch (SQLException e) {
                System.out.print(e);
            }
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cab11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cab11KeyReleased
        String ch="";
        if (!cab11.getText().matches("[0-9]*")||cab11.getText().toString().length()>8) {
            JOptionPane.showMessageDialog(null,"Une erreur est détecté veuillez vérifier la saisi du champ du  télephone.","Erreur !",JOptionPane.ERROR_MESSAGE);
            for(int i=0;i<cab11.getText().length()-1;i++)
            ch=ch+cab11.getText().charAt(i);
            cab11 .setText(ch);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_cab11KeyReleased

    private void cab11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab11ActionPerformed

    private void cab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab2ActionPerformed

    private void cab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab3ActionPerformed

    private void cab1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cab1KeyReleased
        String ch="";
        if (!cab1.getText().matches("[0-9]*")|| cab1 .getText().toString().length()>8) {
            JOptionPane.showMessageDialog(null,"Une erreur est détecté veuillez vérifier la saisi du champ CIN.","Erreur !",JOptionPane.ERROR_MESSAGE);
            for(int i=0;i<cab1.getText().length()-1;i++)
            ch=ch+cab1.getText().charAt(i);
            cab1 .setText(ch);
        }
    }//GEN-LAST:event_cab1KeyReleased

    private void cab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab1ActionPerformed

    private void cab10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab10ActionPerformed

    private void cab10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cab10KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cab10KeyReleased

    private void cab14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cab14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cab14ActionPerformed

    private void cab14KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cab14KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cab14KeyReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                utilisateur dialog = new utilisateur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField cab1;
    private javax.swing.JFormattedTextField cab10;
    private javax.swing.JFormattedTextField cab11;
    private javax.swing.JTextArea cab12;
    private javax.swing.JFormattedTextField cab14;
    private javax.swing.JTextArea cab15;
    private javax.swing.JFormattedTextField cab17;
    private javax.swing.JFormattedTextField cab18;
    private javax.swing.JFormattedTextField cab19;
    private javax.swing.JFormattedTextField cab2;
    private javax.swing.JFormattedTextField cab20;
    private javax.swing.JFormattedTextField cab23;
    private javax.swing.JFormattedTextField cab25;
    private javax.swing.JTextArea cab26;
    private javax.swing.JFormattedTextField cab27;
    private javax.swing.JFormattedTextField cab28;
    private javax.swing.JFormattedTextField cab29;
    private javax.swing.JFormattedTextField cab3;
    private javax.swing.JFormattedTextField cab30;
    private javax.swing.JFormattedTextField cab31;
    private javax.swing.JFormattedTextField cab35;
    private javax.swing.JFormattedTextField cab36;
    private javax.swing.JFormattedTextField cab37;
    private javax.swing.JFormattedTextField cab4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

 void utilisateur()
 {
try {
    //`utilisateur` (`cin`, `nom`, `prenom`, `sexe`, `type`, `identifiant`, `Mot_de_Passe`, `gsm`, `adresse`) VALUES ('44', '4', '4', '4', '4', '4', '4', '4', '4', '444');
cabinetmedical cabinet=new cabinetmedical();
String req_sql = "SELECT * FROM utilisateur";
ResultSet rs_medical = cabinet.statement.executeQuery(req_sql);
String titre [] = { "Cin","Nom", "Prenom", "Sexe","Type ","Telephone","Identifiant","Mot de Passe"};
 int indis = 0; 
rs_medical.last();
String donnee_bd[][] = new String[rs_medical.getRow()][8];
rs_medical.beforeFirst();
 while (rs_medical.next()) { 
donnee_bd[indis][0] = ""+rs_medical.getString(1);
donnee_bd[indis][1] = ""+rs_medical.getString(2);
donnee_bd[indis][2] = ""+rs_medical.getString(3);
donnee_bd[indis][3] = ""+rs_medical.getString(4);
donnee_bd[indis][4] = ""+rs_medical.getString(5);
donnee_bd[indis][5] = ""+rs_medical.getString(8);
donnee_bd[indis][6] = ""+rs_medical.getString(6);
donnee_bd[indis][7] = ""+rs_medical.getString(7); 
 indis++;
}
DefaultTableModel model = new DefaultTableModel(donnee_bd, titre );
jTable1.setModel(model);  
} catch (SQLException ex) {
ex.printStackTrace();
}
}
  
 void utilisateur_type(String type)
 {
try { 
cabinetmedical cabinet=new cabinetmedical();
String req_sql = "SELECT * FROM utilisateur where type='"+type+"'";
ResultSet rs_medical = cabinet.statement.executeQuery(req_sql);
String titre [] = { "Cin","Nom", "Prenom", "Sexe","Type ","Telephone","Identifiant","Mot de Passe"};
 int indis = 0; 
rs_medical.last();
String donnee_bd[][] = new String[rs_medical.getRow()][8];
rs_medical.beforeFirst(); 
 while (rs_medical.next()) { 
donnee_bd[indis][0] = ""+rs_medical.getString(1);
donnee_bd[indis][1] = ""+rs_medical.getString(2);
donnee_bd[indis][2] = ""+rs_medical.getString(3);
donnee_bd[indis][3] = ""+rs_medical.getString(4);
donnee_bd[indis][4] = ""+rs_medical.getString(5);
donnee_bd[indis][5] = ""+rs_medical.getString(8);
donnee_bd[indis][6] = ""+rs_medical.getString(6);
donnee_bd[indis][7] = ""+rs_medical.getString(7); 
 indis++;
}
DefaultTableModel model = new DefaultTableModel(donnee_bd, titre );
jTable1.setModel(model);  
} catch (SQLException ex) {
ex.printStackTrace();
}
}
}
